'use client';

import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto py-8">
      <h1 className="text-2xl font-bold mb-6">Meal Mentor Disclaimer</h1>
      
      <div className="prose dark:prose-invert">
        <p>
          The nutritional information and feedback provided by Meal Mentor is generated by artificial intelligence 
          and is intended for informational purposes only. While we strive for accuracy, the nutritional analysis 
          may vary from actual values and should not be considered a substitute for professional medical or 
          nutritional advice.
        </p>
        
        <p>
          Users with specific dietary requirements, food allergies, medical conditions, or nutritional concerns 
          should consult with qualified healthcare professionals before making significant changes to their diet 
          based on Meal Mentor&apos;s feedback.
        </p>
        
        <p>
          Meal Mentor does not guarantee the accuracy, completeness, or usefulness of any information provided 
          and is not responsible for any actions taken based on this information. By using this application, 
          you acknowledge and agree that you use the nutritional feedback at your own risk.
        </p>
        
        <p className="mt-8">
          © 2025 Meal Mentor. All Rights Reserved.
        </p>
      </div>
      
      <div className="mt-8">
        <Link 
          href="/"
          className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300"
        >
          ← Back to Home
        </Link>
      </div>
    </div>
  );
} 